### ISSUE TITLE
Is it possible to use webchimera inside the browser

### ISSUE THREAD

**Issue by dedesite** [RSATom/WebChimera.js#104]
Sorry if this question has been answered or is not relevant but I can't find a good answer.

I wonder why libVLC couln't be transcode in js (using Emscripten I presume) and use directly inside the browser to play all video and display them inside a canvas ?
Is their a technical limitation to that ?

Again, sorry if it has already been discuss.

**Comment by RSATom** [comment]
`WebChimera.js` could not be used in browsers, just by design. You could try use older project [`WebChimera`](https://github.com/RSATom/WebChimera) - but it's deprecated, and could be used only in Firefox atm.

> I wonder why libVLC couln't be transcode in js (using Emscripten I presume) and use directly inside the browser to play all video and display them inside a canvas ?
Is their a technical limitation to that ?

Just because it's not so simple task. libvlc and plugins heavily rely on multithreading and low level OS functions. So it's not only about transcode C/C++ code to JS (with Emscripten or WebAssembly), but more about port `libvlc`, plugins and all related libraries to new platform. And this platform totally different from any existent desktop platforms.

**Comment by dedesite** [comment]
Thanks for the quick reply,

So, as I understand it is theoretically possible to play any type of codec and containers inside the browser (without plugin) but it would need a huge amount of work to get libVlc or gstreamer to be ported to ES6.

I knew the Webchimera plugin but wander if there wasn't any "new" and not deprecated solutions to get the same result.

**Comment by RSATom** [comment]
> So, as I understand it is theoretically possible to play any type of codec and containers inside the browser (without plugin) but it would need a huge amount of work to get libVlc or gstreamer to be ported to ES6.

Yes. JavaScript is full featured language, so you can get with it anything you like. The only question is perfomance and required amount of work.

**Comment by dedesite** [comment]
> Yes. JavaScript is full featured language, so you can get with it anything you like. The only question is perfomance and required amount of work.

Thanks, and do you know if such a work is attempting by people or is it something that nobody has interest in ?

**Comment by RSATom** [comment]
Don't think it's possible to do by any single man or even small group of developers. It's really too huge amount of work. Maybe somebody works on it, but I hear nothing about something similar.

**Comment by dedesite** [comment]
Ok :) so I can close de question. Keep your good work on webchimera.
