### ISSUE TITLE
Transition to OpenGLES2->WebGL (instead of vmem->canvas)

### ISSUE THREAD

**Issue by romaincointepas** [RSATom/WebChimera.js#116]
WebChimera.js currently uses `vmem` which is suboptimal for 2 reasons:
- [`vmem` implementation starting with VLC 3.0 is incompatible with how WebChimera.js currently works.](https://github.com/RSATom/WebChimera.js/issues/110#issue-185615873)
- Using `vmem` is pretty bad performance-wise (huge CPU usage).

Switching from `vmem->canvas` to `OpenGLES2->WebGL` [seems to be the way to go.](https://github.com/RSATom/WebChimera.js/issues/110#issuecomment-269457667)

However, passing the OpenGL context to node addons [seems to be tricky](https://github.com/RSATom/WebChimera.js/issues/110#issuecomment-269464001). I'm wondering if the Electron team (@zcbenz, @kevinsawicki) has some thoughts on that.

Also cc'ing @jbkempf (president of VideoLAN) as he jumped in the other issue thread regarding this.

@RSATom On a related note, I (and I think a few others) would definitely be happy to *chip in* financially to cover costs and, well, show our gratitude and our desire to see you continue working on this project!

*Also cc'ing @jaruba, @RiderSx from other thread.*

**Comment by lewmpk** [comment]
+1
would be happy to chip in and help where i can

**Comment by Ivshti** [comment]
Also I'm referencing this:
https://github.com/RSATom/WebChimera.js/wiki/Limitations-(Read-this-for-Android-%7C-Raspberry-Pi-%7C-performance-issues

Solving this issue would almost 100% require help from the Electron team though. 

the reason is that @RSATom and myself did a extensive, in-depth research a year ago on how VLC can work better with Electron, and almost nothing popped up, especially in the context of node.js modules + Electron. The whole system is very complex and also different components are well isolated. Another reason you cannot simply "get an opengl context" is that the whole Chromium architecture relies on ANGLE, which means that the bottom layer may be OpenGL, but may also be DirectX, so there's no such thing as guaranteed OpenGL context.

PPAPI would deliver better rendering easily, but it would require VLC to be compiled to NaCL (@jbkempf, ideas?)

**Comment by Ivshti** [comment]
An architecture that certainly WOULD work though is to get CEF/Chromium to render off-screen, get the texture from that, and manually overlay it yourself over VLC, using your own VLC vout plugin. However, this goes against the architecture of Electron.

**Comment by jbkempf** [comment]
So, using vmem is a fun trick, but is never a good idea because:
- it involves memcpy, and "memcpy is murder", and sometimes 2 memcpy;
- it involves doing I420->RGB in software, often using swscale, which is very slow too;
- it destroys all hardware decoding possible... And that is a killer for limited machines, like rPI or light notebooks, when playing 4K...

For numerous reasons, we're putting a lot of time to improve OpenGL and OpenGLES2 support in VLC, but one of the main reasons is that we hope to use OpenGLES2 to get video output in WebGL for the VLC.js project. Indeed emscripten can convert OpenGLES2 into WebGL.

There are several solutions to go forward:
- give the xid/HWND to draw to libVLC, but am not sure this is doable in a CEF context, since maybe those are not true Windows;
- give the OpenGL (respectively D3D) CEF context to libVLC and hack the vlc output to understand those and draw into those;
- work on the PPAPI VLC code and clean it to release a final form (I might be able to sponsor this work, if a good C++ developer arrives);
- hope on VLC.js, but that is a long moonshot and will be very slow, IMHO.

**Comment by Ivshti** [comment]
@jbkempf I'd like to add that with Electron (Chromium's) architecture this actually involves copying a texture from one (renderer) to another (gpu) process. Which is not only murder, but massacre :)  

At we worked around I420->RGB by using l420 converting it with WebGL shaders

"give the OpenGL (respectively D3D) CEF context to libVLC and hack the vlc output to understand those and draw into those;" - this sounds the most realistic I think, other than the PPAPI

**Comment by jbkempf** [comment]
@Ivshti so is there any way to get those OpenGL/D3D context? Could VLC run in the GPU process?

**Comment by jaruba** [comment]
![erobftm](https://cloud.githubusercontent.com/assets/1777923/22862791/16a5820e-f13e-11e6-8385-5c6a6e3de024.gif)

**Comment by RSATom** [comment]
> give the xid/HWND to draw to libVLC, but am not sure this is doable in a CEF context, since maybe those are not true Windows;

I think @asherkin could say something useful about it

**Comment by romaincointepas** [comment]
I found this repo: https://github.com/Kagami/boram.

As far as I can tell, it uses electron + [a (small) custom pepper plugin](https://github.com/Kagami/boram/blob/master/src/mpv/interop.cc) + [mpv](https://mpv.io) to enable access to OpenGL in electron (so mpv can draw on it).

Thoughts?

**Comment by jbkempf** [comment]
Yes, clearly doable in VLC.

Also, since this morning, we have the core of a working vlc-nacl/ppapi project. Interesting?

**Comment by romaincointepas** [comment]
@jbkempf Awesome! Could you share the link?

**Comment by jbkempf** [comment]
@romaincointepas link to ppapi?

**Comment by romaincointepas** [comment]
@jbkempf Yep! I tried to find the repo, nothing came up (I was hoping it was public as I'm really interested in following the work on this and try it early).

**Comment by jbkempf** [comment]
@romaincointepas so far, it's a bit private, but I will share it soon.

**Comment by Kagami** [comment]
Extracted boram's plugin to [separate repo](https://github.com/Kagami/mpv.js). You might look at its approach (basically same as described above).

**Comment by jbkempf** [comment]
Patches for PPAPI are on vlc-devel mailing list.

**Comment by LukasBombach** [comment]
This is awesome, @Kagami . And while we are at it, I want to express my appreciation for the WebChimera-project, @RSATom and @jaruba , I have been following this for a while and you really put a lot of effort in this awesome project, thanks!

Apart from that: Does VLC have any benefits over mpv?

**Comment by RSATom** [comment]
Closed as too old.
