### ISSUE TITLE
Performance on Raspberry Pi (2)

### ISSUE THREAD

**Issue by npenin** [RSATom/WebChimera.js#49]
Hi,

I am concerned about performances on my RPi2, which, is not able to draw any video frame. Maybe there could be another solution that I have not imagined yet. Here are the two options I could imagine so far :

- Vlc has an SDL video module. Do you think it could be possible to use this SDL module to render to canvas ? maybe using emscripten ? 

- Otherwise, would a virtual framebuffer do the trick ? The question is then how do draw this virtual frame buffer to html canvas.

Thanks.

**Comment by jaruba** [comment]
maybe the issue is with how/if webgl works on the rpi2

**Comment by Ivshti** [comment]
Trust me, there's no way to improve performance with electron or anything chrome based.

I've spent many hours on it.

The problems with all your ideas are that they still pass through canvas, which itself is the issue.

In chromium, when we pass a video frame buffer to webgl to be uploaded to the GPU, it first gets sent to another process - the GPU process. So we have memory copying for every frame.

The way webchimera.js works, even without the multi process overhead of chromium, is incorrect for the rpi. The rpi has full hardware acceleration for a few codecs, and VLC cannot take full advantage of that.

Maybe the situation will improve slightly when we have PBOs in webgl, since chromium may figure out a way to upload the texture from one process and use it in another.

For now, all you can do is go through chromium a flags and find some experimental feature that will speed up texture upload. Research it

**Comment by Ivshti** [comment]
@jaruba it's probably a good idea to find all my posts explaining this and put them in the wiki so as to not explain it again

**Comment by RSATom** [comment]
It's possible poor performance on rpi has another reason - x11 on rpi doesn't support hardware acceleration. So Chromium can't use it. The only solution is use some fullscreen OpenGL based application (maybe even it could be Electron/NW.js, since it could use OpenGL acceleration itself)

**Comment by RSATom** [comment]
maybe using Wayland could be solution, but I don't know if it accessible on rpi

**Comment by Ivshti** [comment]
Yeah, that too - X11 is usually poor under the raspberry. So a starting point would be to make electron and by extension chromium work in frame buffer, accelerated mode.

Then with the modern rpi performance it would probably play standard res videos fine, but it's still a bad idea

**Comment by RSATom** [comment]
I think it's not solvable without hardware acceleration support in X11 on RPI
