### ISSUE TITLE
How to set hardware decoding

### ISSUE THREAD

**Issue by jayke-vbh** [RSATom/WebChimera.js#82]
Hi,

I'm using `wcjs-player`, so please let me know if this issue should be posted there. I followed the path the VLC options take down to WebChimera.js so that's why I assume it is an issue for here.

I'd like to use the parameter `--avcodec-hw=vaapi` on Linux, as this shows a huge difference for CPU load in the standalone VLC (50% vs 15%). However, this parameter does not have any effect if I pass it on to `wcjs-player` (subsequently going through `wcjs-renderer` to WebChimera.js).

I think the reason this does not work is stated here: http://stackoverflow.com/questions/34675182/how-to-enable-hardware-accelerated-decoding-in-libvlc. It seems the way to call this parameter has been changed since LibVLC 2.2.x. Looking at the WebChimera.js source, there is no `libvlc_media_add_option` used anywhere, so I'm assuming it's not currently possible to use this option. Is this something that could be changed (and would this even have any effect given the way WebChimera.js works?)

**Comment by RSATom** [comment]
`WebChimera.js` is too different from VLC by rendering architecture and I think hardware acceleration can't give any significant benefits to it. The reason is `WebChimera.js` has to decode video frames to memory, to be able pass it to Java Script. By other side hardware acceleration has best effect if video frames decoded on GPU, and don't leave GPU memory before rendering. Passing data from GPU memory to CPU memory (and vice versa) is very expensive operation, and it eats all benefits from decoding on GPU.

What about `libvlc_media_add_option` - it's used in `WebChimera.js` and additional options could be passed via [ VlcPlaylist ::addWithOptions(mrl, options)](https://github.com/RSATom/WebChimera.js/wiki/JavaScript-API#vlcplaylist). You didn't find it just because [it's in subrepo](https://github.com/RSATom/ya-libvlc-wrapper/blob/master/vlc_media.cpp#L47)

**Comment by Ivshti** [comment]
Please see
https://github.com/RSATom/WebChimera.js/wiki/Limitations-(Read-this-for-Android-%7C-Raspberry-Pi-%7C-performance-issues)

**Comment by jayke-vbh** [comment]
Thanks for the quick reply, I understand!
