### ISSUE TITLE
VLC 2.2.4

### ISSUE THREAD

**Issue by fleex** [RSATom/WebChimera.js#87]
Just a friendly request, would it be possible to get a new release with VLC 2.2.4?

Also, support for the latest Electron version before the 1.0 switch (v0.37.8) would be awesome (the latest release supported v0.37.6, not exactly sure why...)

Thanks in advance!

**Comment by RSATom** [comment]
@Ivshti, @jaruba do you still need `wcjs` for Electron versions older than v0.37.8?

**Comment by jaruba** [comment]
I'm using Electron v0.37.6 on Win + OSX and Electron v0.36.7 on Linux.. They seem to work well enough for now, so, I'd say no (for the moment at least..)

**Comment by RSATom** [comment]
@jaruba, is it ok of you up Electron version to v0.37.8?

**Comment by jaruba** [comment]
@RSATom I just made a pre-release less then a week ago, I still have a lot of bugs to fix on all platforms, so I wouldn't play with fire by switching to a different Electron version too now..

**Comment by jaruba** [comment]
And there's also the fact that Linux only works with Electron v0.36.7 or less, so the farther I go from this version with Win + OSX, the more chances of running into Electron API changes that won't be available in Linux.

The only reason I'm using v0.37.6 on Win + OSX is for one particular Electron API method that doesn't support Linux anyway.. I'm pretty much stuck on these versions because of cross-platform compatibility, I can only hope they don't have any serious bugs.

**Comment by guidupuy** [comment]
As far as fleex is concerned, I actually think it's fine if you skip v0.37.8.

I wanted to upgrade to the latest version of Electron anyway - the only thing that prevented me from doing that with your last release was a bug with Electron. Someone had opened an issue, so it's probably fixed by now.

**Comment by RSATom** [comment]
@guidupuy, what exactly bug do you mean?

**Comment by guidupuy** [comment]
@RSATom no worries, I was referring to a bug with Electron, not WebChimera ;-)

**Comment by RSATom** [comment]
it's good :)

**Comment by RSATom** [comment]
Will be available soon: https://github.com/RSATom/WebChimera.js/releases/tag/v0.2.6
